services:
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    command: tritonserver --model-repository=/models
    ports:
     - 8000:8000
     - 8001:8001
     - 8002:8002
    volumes:
      - /models:/models
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  tritonclient:
    image: nvcr.io/nvidia/tritonserver:24.08-py3-sdk
    command: pip install torchvision && python3 /workspace/client.py
    volumes:
      - ./:/workspace/
    network_mode: "host"
    depends_on:
      tritonserver:
        condition: service_started